package pojo;
// Generated Oct 15, 2022 1:45:55 PM by Hibernate Tools 4.3.1

import DAO.DAOuser;
import java.util.List;
import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;




/**
 * TblStock generated by hbm2java
 */
@ManagedBean
public class TblStock  implements java.io.Serializable {


     private Integer idBarang;
     private String namaHelm;
     private String jenisHelm;
     private String stockHelm;
     
     public List <TblStock> getAllRecords()
     {
         DAOuser stk = new DAOuser();
         List <TblStock> lStock = stk.retrieveTblStock();
         return lStock;
     }
     //fungsi search
     public String getById()
     {
         String id_barang = idBarang.toString();
         DAOuser stk = new DAOuser();
         List <TblStock> lStock = stk.getbyID(id_barang);
         namaHelm = lStock.get(0).namaHelm;
         jenisHelm = lStock.get(0).jenisHelm;
         stockHelm = lStock.get(0).stockHelm;
         return "adminmenu.xhtml";
     }
     //fungsi edit
     public void edit()
     {
         DAOuser stk = new DAOuser();
         stk.editStock(this);
         namaHelm = "";
         jenisHelm = "";
         stockHelm = "";
         FacesMessage faceMessages = new FacesMessage(FacesMessage.SEVERITY_INFO,"Edit Data Berhasil",null);
     }
     
     public void delete()
     {
         //String id_barang = idBarang.toString();
         DAOuser stk = new DAOuser();
         stk.deleteStock(idBarang);
         namaHelm = "";
         jenisHelm ="";
         stockHelm = "";
     }

    public TblStock() {
    }

    public TblStock(String namaHelm, String jenisHelm, String stockHelm) {
       this.namaHelm = namaHelm;
       this.jenisHelm = jenisHelm;
       this.stockHelm = stockHelm;
    }
   
    public Integer getIdBarang() {
        return this.idBarang;
    }
    
    public void setIdBarang(Integer idBarang) {
        this.idBarang = idBarang;
    }
    public String getNamaHelm() {
        return this.namaHelm;
    }
    
    public void setNamaHelm(String namaHelm) {
        this.namaHelm = namaHelm;
    }
    public String getJenisHelm() {
        return this.jenisHelm;
    }
    
    public void setJenisHelm(String jenisHelm) {
        this.jenisHelm = jenisHelm;
    }
    public String getStockHelm() {
        return this.stockHelm;
    }
    
    public void setStockHelm(String stockHelm) {
        this.stockHelm = stockHelm;
    }




}


